msbuild:
  image: registry.gitlab.com/cafstep/dotvvm-test/dotvvm
  stage: build
  script:
    - cd $CI_PROJECT_DIR/src/DotVVM.Framework
        && npm ci --cache $CI_PROJECT_DIR/.npm --prefer-offline
        && npm run build
        && cd $CI_PROJECT_DIR/src
        && dotnet restore --packages $CI_PROJECT_DIR/.nuget DotVVM.sln
        && dotnet build --no-restore DotVVM.sln
  cache:
    paths:
      - .npm/
      - .nuget/
  only:
    - gitlab-ci-test
