msbuild:
  image: registry.gitlab.com/cafstep/dotvvm-test/dotvvm
  stage: build
  script:
    - cd src/DotVVM.Framework && npm install && npm run build && cd ../..
    - dotnet build ./src/DotVVM.sln
  only:
    - gitlab-ci-test
