variables:
  DOTVVM_ROOT: $CI_PROJECT_DIR
  DISPLAY: ":42"

default:
  cache:
    paths:
      - .npm/
      - .nuget/
  artifacts:
    paths:
      - artifacts/

build-solution:
  image: registry.gitlab.com/cafstep/dotvvm-test/dotvvm
  stage: build
  script:
    - cd $DOTVVM_ROOT/src/DotVVM.Framework
        && npm ci --cache $DOTVVM_ROOT/.npm --prefer-offline
        && npm run build
        && cd $DOTVVM_ROOT/src
        && dotnet restore --packages $DOTVVM_ROOT/.nuget Crossplatform.sln
        && dotnet build --no-restore --configuration Release Crossplatform.sln
  only:
    - ci-test

run-unit-tests:
  image: registry.gitlab.com/cafstep/dotvvm-test/dotvvm
  stage: test
  script:
    - dotnet test $DOTVVM_ROOT/src/DotVVM.Framework.Tests.Common
        --no-build
        --logger "junit;LogFilePath=$DOTVVM_ROOT/artifacts/Common.JUnit.xml"
        --configuration Release
  artifacts:
    reports:
      junit: artifacts/**/*.JUnit.xml
  only:
    - ci-test

run-ui-tests:
  image: registry.gitlab.com/cafstep/dotvvm-test/dotvvm
  stage: test
  script:
    - Xvfb $DISPLAY -screen 0 800x600x16 &
    - dotnet run --project $DOTVVM_ROOT/src/DotVVM.Samples.BasicSamples.AspNetCoreLatest
        --no-build
        --configuration Release
        --urls http://localhost:16018/ &
    - dotnet test $DOTVVM_ROOT/src/DotVVM.Samples.Tests
        --no-build
        --logger "junit;LogFilePath=$DOTVVM_ROOT/artifacts/Samples.JUnit.xml"
        --configuration Release
  artifacts:
    reports:
      junit: artifacts/**/*.JUnit.xml
  only:
    - ci-test
