name: setup
description: Sets up the build environment for the DotVVM repo.

inputs:
  sln:
    default: src/DotVVM.sln
    description: Path to a Visual Studio solution
    required: false
  azure-artifacts-feed:
    required: false
    description: An URL to an Azure Artifacts NuGet feed
  azure-artifacts-pat:
    required: false
    description: A PAT to publish on Azure Artifacts

runs:
  using: composite
  steps:
  # nuget
  - uses: actions/cache@v2
    with:
      path: ~/.nuget/packages
      key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
      restore-keys: |
        ${{ runner.os }}-nuget-

  # Node.js
  - uses: actions/setup-node@v2
    with:
      node-version: 16
  - run: |
      corepack enable
      yarn set version stable
    shell: bash

  # .NET
  - uses: actions/setup-dotnet@v1
    with:
      dotnet-version: |
        5.0.x
        6.0.x
      source-url: ${{ env.AZURE_ARTIFACTS_FEED_URL }}
    env:
      NUGET_AUTH_TOKEN: ${{ inputs.azure-artifacts-pat }}
  - if: ${{ runner.os == 'Windows' }}
    uses: microsoft/setup-msbuild@v1.1

  # restore packages
  - if: ${{ runner.os == 'Windows' }}
    uses: nuget/setup-nuget@v1
  - if: ${{ runner.os == 'Windows' }}
    run: msbuild ${{ inputs.sln }} -t:Restore
    shell: pwsh
  - if: ${{ runner.os != 'Windows' }}
    run: dotnet restore ${{ inputs.sln }}
    shell: bash
