name: DotVVM CI

on:
  push:
    branches:
      - ci-test

jobs:
  build-solution:
    runs-on: ubuntu-latest
    container: registry.gitlab.com/cafstep/dotvvm-test/dotvvm
    env:
      DOTVVM_ROOT: $GITHUB_WORKSPACE
      DISPLAY: :42
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: $GITHUB_WORKSPACE/.npm
          key: npm-${{ hashFiles('src/DotVVM.Framework/package-lock.json') }}
      - uses: actions/cache@v2
        with:
          path: $GITHUB_WORKSPACE/.nuget
          key: nuget
      - run: npm ci --cache $GITHUB_WORKSPACE/.npm --prefer-offline
        working-directory: ./src/DotVVM.Framework
      - run: npm run build
        working-directory: ./src/DotVVM.Framework
      - run: dotnet restore --packages $GITHUB_WORKSPACE/.nuget Crossplatform.sln
        working-directory: ./src
      - run: dotnet build --no-restore --configuration Release Crossplatform.sln
        working-directory: ./src
      - uses: actions/upload-artifact@v2
        with:
          name: built-solution
          path: artifacts/

# Built with ❤ by [Pipeline Foundation](https://pipeline.foundation)
