name: Publish packages

on:
  workflow_dispatch:
    inputs:
      push-internal-feed:
        type: boolean
        default: true
        description: Push to internal feed?
        required: true
      push-public-feed:
        type: boolean
        default: false
        description: Push to NuGet.org?
        required: true
      major:
        type: string
        default: "4"
        description: Major version
        required: true
      minor:
        type: string
        default: "0"
        description: Minor version
        required: true
      patch:
        type: string
        default: "0"
        description: Patch version
        required: true
      preview:
        type: string
        default: ""
        description: Preview number
        required: false
      is-final-preview:
        type: boolean
        default: false
        description: Is this a final preview version?
        required: true
      use-build-number:
        type: boolean
        default: true
        description: Append the build number?
        required: true
      additional-suffix:
        type: string
        default: ""
        description: Additional suffix
        required: false

env:
  AZURE_ARTIFACTS_FEED_URL: https://pkgs.dev.azure.com/rigantitfs/DotVVM/_packaging/GitHubPublishTest/nuget/v3/index.json

jobs:
  pack-projects:
    name: Pack projects
    runs-on: windows-2022
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v2

    - name: Set up
      uses: ./.github/setup
      with:
        azure-artifacts-feed: ${{ env.AZURE_ARTIFACTS_FEED_URL }}
        azure-artifacts-pat: ${{ secrets.AZURE_ARTIFACTS_PAT }}

    - name: Compose version
      run: >
        $version = $(./.github/workflows/ComposeVersion.ps1
          -major "${{ inputs.major }}"
          -minor "${{ inputs.minor }}"
          -patch "${{ inputs.patch }}"
          -preview "${{ inputs.preview }}"
          -buildNumber "${{ github.run_id }}"
          -additionalSuffix ${{ inputs.additionalSuffix }}
          -isFinalPreview ${{ inputs.is-final-preview }}
          -useBuildNumber ${{ inputs.use-build-number }}) ;
        echo "Version is set to '$version'" ;
        echo "DOTVVM_VERSION=$version" >> $GITHUB_ENV

    - name: DotVVM.Core
      uses: ./.github/pack
      with:
        project: src/Framework/Core

    - name: DotVVM
      uses: ./.github/pack
      with:
        project: src/Framework/Framework

    - name: DotVVM.Owin
      uses: ./.github/pack
      with:
        project: src/Framework/Hosting.Owin

    - name: DotVVM.AspNetCore
      uses: ./.github/pack
      with:
        project: src/Framework/Hosting.AspNetCore

    - name: DotVVM.CommandLine
      uses: ./.github/pack
      with:
        project: src/Tools/CommandLine

    - name: DotVVM.Tools.StartupPerf
      uses: ./.github/pack
      with:
        project: src/Tools/StartupPerfTester

    - name: DotVVM.Api.Swashbuckle.AspNetCore
      uses: ./.github/pack
      with:
        project: src/Api/Swashbuckle.AspNetCore

    - name: DotVVM.Api.Swashbuckle.Owin
      uses: ./.github/pack
      with:
        project: src/Api/Swashbuckle.Owin

    - name: DotVVM.HotReload
      uses: ./.github/pack
      with:
        project: src/Tools/HotReload/Common

    - name: DotVVM.HotReload.AspNetCore
      uses: ./.github/pack
      with:
        project: src/Tools/HotReload/AspNetCore

    - name: DotVVM.HotReload.Owin
      uses: ./.github/pack
      with:
        project: src/Tools/HotReload/Owin

    - name: DotVVM.Testing
      uses: ./.github/pack
      with:
        project: src/Framework/Testing

    - name: DotVVM.DynamicData
      uses: ./.github/pack
      with:
        project: src/DynamicData/DynamicData

    - name: DotVVM.DynamicData.Annotations
      uses: ./.github/pack
      with:
        project: src/DynamicData/Annotations

    - name: DotVVM.Tracing.ApplicationInsights
      uses: ./.github/pack
      with:
        project: src/Tracing/ApplicationInsights

    - name: DotVVM.Tracing.ApplicationInsights.AspNetCore
      uses: ./.github/pack
      with:
        project: src/Tracing/ApplicationInsights.AspNetCore

    - name: DotVVM.Tracing.ApplicationInsights.Owin
      uses: ./.github/pack
      with:
        project: src/Tracing/ApplicationInsights.Owin

    - name: DotVVM.Tracing.MiniProfiler.AspNetCore
      uses: ./.github/pack
      with:
        project: src/Tracing/MiniProfiler.AspNetCore

    - name: DotVVM.Tracing.MiniProfiler.Owin
      uses: ./.github/pack
      with:
        project: src/Tracing/MiniProfiler.Owin

    - name: Publish to the internal feed
      run: >
        Get-ChildItem -Path "${{ github.workspace}}/artifacts/packages" -Filter "*.nupkg" | ForEach-Object {
          dotnet nuget push --api-key AzureArtifacts --source "${{ env.AZURE_ARTIFACTS_FEED_URL }}" $_.FullName
        }
      working-directory: ${{ github.workspace }}
      if: ${{ inputs.push-internal-feed }}

    - name: Publish to the public feed
      run: >
        Get-ChildItem -Path "${{ github.workspace}}/artifacts/packages" -Filter "*.nupkg" | ForEach-Object {
          Write-Host "Pretending to push '$($_.FullName)' to NuGet.org."
        }
      working-directory: ${{ github.workspace }}
      if: ${{ inputs.push-public-feed }}
